### ISSUE TITLE
compilation with ghc-9.12 fails

### ISSUE THREAD

**Issue by jwaldmann** [bruderj15/Hasmtlib#125]
```
$ cabal install hasmtlib-2.8.1 --allow-newer -w /opt/ghc/ghc-9.12.2/bin/ghc
...
[19 of 29] Compiling Language.Hasmtlib.Internal.Parser ( src/Language/Hasmtlib/Internal/Parser.hs, dist/build/Language/Hasmtlib/Internal/Parser.o, dist/build/Language/Hasmtlib/Internal/Parser.dyn_o )
src/Language/Hasmtlib/Internal/Parser.hs:148:32: error: [GHC-25897]
    • Could not deduce ‘enc ~ Unsigned’
      from the context: (t ~ BvSort enc n, KnownBvEnc enc, KnownNat n)
        bound by a pattern with constructor:
                   SBvSort :: forall (enc :: BvEnc) (n :: Nat).
                              (KnownBvEnc enc, KnownNat n) =>
                              Proxy enc -> Proxy n -> SSMTSort (BvSort enc n),
                 in a case alternative
        at src/Language/Hasmtlib/Internal/Parser.hs:148:15-27
      Expected: Data.Attoparsec.Internal.Types.Parser ByteString (Expr t)
        Actual: Data.Attoparsec.Internal.Types.Parser
                  ByteString (Expr (BvSort Unsigned n))
      ‘enc’ is a rigid type variable bound by
        a pattern with constructor:
          SBvSort :: forall (enc :: BvEnc) (n :: Nat).
                     (KnownBvEnc enc, KnownNat n) =>
                     Proxy enc -> Proxy n -> SSMTSort (BvSort enc n),
        in a case alternative
        at src/Language/Hasmtlib/Internal/Parser.hs:148:15-27
    • In the expression:
        unary "bvnot" not <|> binary "bvand" (&&) <|> binary "bvor" (||)
...
```

it does work with ghc-9.10.3, and with ghc-9.14.0.20251104

**Comment by bruderj15** [comment]
Yeah I can reproduce this. Seems like ghc-9-12.2 is somewhat finicky with the type-unification.
I couldn't give it a quick fix.

Will look into it when there's some spare time.

**Comment by jwaldmann** [comment]
bug also occurs with ghc-9.12.2.20251110 (= ghc-9.12.3-rc2)

**Comment by jwaldmann** [comment]
bug goes away with 9.14. this succeeds:

```
cabal install hasmtlib-2.8.1 --allow-newer=base,template-haskell -w /opt/ghc/ghc-9.14.1/bin/ghc
```
so, the work-around is to just avoid 9.12
